### ISSUE TITLE
New module: Sequali

### ISSUE THREAD

**Issue by MatthiasZepper** [nf-core/seqinspector#30]
### Description of feature

Write a new nf-core module for [Sequali](https://github.com/rhpvorderman/sequali) and add it to the pipeline.

**Comment by DarkoCucin** [comment]
https://github.com/nf-core/modules/pull/6896 - Link to the pull request.

**Comment by irliampa** [comment]
Pull request has now been merged to nf-core/modules! I am changing the status to DONE! Yaay @DarkoCucin !!! 💯 🚀

**Comment by DarkoCucin** [comment]
@irliampa We nailed it! 💯 🚀
