### ISSUE TITLE
Speed up nf-test CI by excluding modules

### ISSUE THREAD

**Issue by kedhammar** [nf-core/seqinspector#61]
### Description of feature

Future improvement for https://github.com/nf-core/seqinspector/pull/51

See https://github.com/nf-core/seqinspector/pull/51#issuecomment-2444009157 and
https://github.com/Aratz/seqinspector/commit/3aafa25bec9a9669cfd6fb556de82580d27c0e28
https://github.com/Aratz/seqinspector/commit/0017c06ea1a5a0bfde58bc1868545e84aae1946d
https://github.com/Aratz/seqinspector/commit/83da64ccc022873e284afebeef01594be6bd530d

**Comment by Aratz** [comment]
This was solved in https://github.com/nf-core/seqinspector/pull/53#issuecomment-2462189719
